# Generated by Django 5.0.8 on 2024-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TweetApp', '0003_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
